version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1-stretch
    working_directory: /go/src/github.com/cybozu-go/placemat
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y qemu-utils
      - run: go get github.com/golang/lint/golint
      - run: (! goimports -d . 2>&1 | read _)
      - run: $GOPATH/bin/golint -set_exit_status ./...
      - run: go get -v -t -d ./...
      - run: go test -race -v ./...
