version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.10-bionic
    working_directory: /go/src/github.com/cybozu-go/placemat
    steps:
      - checkout
      - run: apt-get update && apt-get install -y qemu-utils
      - run: go get -v -t -d ./...
      - run: (! goimports -d . 2>&1 | read _)
      - run: test $(golint ./... | grep -v "returns unexported type" | wc -l) -eq 0
      - run: go test -race -v ./...
