version: 2.1
commands:
  run-mtest:
    description: "multi-host test"
    parameters:
      suite:
        type: string
      target:
        type: string
        default: ""
    steps:
      - run:
          name: Store Service Account
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT > account.json
            gcloud auth activate-service-account --key-file=account.json
      - run:
          command: |
            ./bin/run-mtest.sh <<parameters.suite>> <<parameters.target>>
      - run:
          name: Set the instance lifetime to 10 minutes
          command: |
            . ./bin/env
            $GCLOUD compute instances add-metadata ${INSTANCE_NAME} --zone ${ZONE} \
              --metadata shutdown-at=$(date -Iseconds -d+10minutes)
          when: on_fail
      - run:
          name: notify to slack
          command: |
            curl -X POST -H 'Content-type: application/json' --data "{ \
              \"blocks\": [ \
                { \
                  \"type\": \"section\", \
                  \"text\": { \
                    \"type\": \"mrkdwn\", \
                    \"text\": \"${CIRCLE_JOB} was failed. Do you extend the lifetime of ${INSTANCE_NAME}?\" \
                  }, \
                  \"accessory\": { \
                    \"type\": \"button\", \
                    \"text\": { \
                      \"type\": \"plain_text\", \
                      \"text\": \"Extend\", \
                      \"emoji\": true \
                    }, \
                    \"value\": \"${INSTANCE_NAME}\" \
                  } \
                } \
              ]\
            }" $SLACK_WEBHOOK_URL
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    steps:
      - checkout
      - run: make SUDO="" setup
      - run: make test
      - run: make deb VERSION=${CIRCLE_TAG:-v0.1}
      - persist_to_workspace:
          root: .
          paths:
            - "*.deb"
  mtest:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run-mtest:
          suite: ./functions
  publish-github-release:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} ./artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - mtest:
          filters:
            tags:
              only: /^v.*/
      - publish-github-release:
          requires:
            - build
            - mtest
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
