version: 1
config:
- type: physical
  name: ens3
  subnets:
  - type: static
    address: 172.16.0.11
    netmask: 255.255.255.0
    routes:
    - network: 0.0.0.0
      netmask: 0.0.0.0
      gateway: 172.16.0.1
- type: nameserver
  address: [8.8.8.8, 8.8.4.4]
